spring:
  security:
    oauth2:
      client:
        registration:
          nogoodoauth2:
            client-id: YOURID
            client-secret: YOURSECRET
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: https://yourhost/path/to/your/auth/login
        provider:
          nogoodoauth2:
            authorization-uri: https://theirhost/path/to/oauth/authorize
            token-uri: https://theirhost/path/to/oauth/token
            user-info-uri: https://theirhost/path/to/userinfo
            user-name-attribute: name
  thymeleaf:
    cache: false
  cache:
    type: NONE
    
server: 
  port: 8080
             
             
